theme: jekyll-theme-merlot
title: Computer Vision<br/> Ball Avoidance Game
description: Our game takes the simple concept of a tag game to the next level. Users move a real-life rectangle around within the frame of their webcam to move around a virtual representation of this rectangle (created using CV). The user must move around their real-life rectangle so that the virtual rectangle avoids getting tagged by a virtual ball.
